include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/generated_plugin_registrant.dart"
  language:
    strict-casts: false
    strict-inference: false
    strict-raw-types: false
  errors:
    invalid_annotation_target: ignore
    deprecated_member_use: warning
    todo: ignore
  plugins:
    - custom_lint

linter:
  rules:
    avoid_print: true
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    prefer_final_locals: true
    prefer_single_quotes: true
    use_key_in_widget_constructors: true
    sized_box_for_whitespace: true
    avoid_unnecessary_containers: true
    require_trailing_commas: true
